// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID        int64   `json:"id"`
	BookTitle *string `json:"book_title"`
}

type Shop struct {
	ID       int64   `json:"id"`
	ShopName *string `json:"shop_name"`
	Books    []*Book `json:"books"`
}
