// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"app/pagination"
	"strings"
)

func BookOrderToPaginationOrders(orders []*BookOrder) []*pagination.Order {
	paginationOrders := make([]*pagination.Order, len(orders))

	for i, o := range orders {
		paginationOrders[i] = &pagination.Order{Field: strings.ToLower(string(*o.Field)), Direction: pagination.Direction(*o.Direction)}
	}

	return paginationOrders
}
func ShopOrderToPaginationOrders(orders []*ShopOrder) []*pagination.Order {
	paginationOrders := make([]*pagination.Order, len(orders))

	for i, o := range orders {
		paginationOrders[i] = &pagination.Order{Field: strings.ToLower(string(*o.Field)), Direction: pagination.Direction(*o.Direction)}
	}

	return paginationOrders
}
