[psql]
  dbname = "graphql"
  host   = "postgres"
  port   = 5432
  user   = "graphql"
  pass   = "graphql"
  sslmode = "disable"
  schema = "graphql"

[imports.all]
  standard = [
    '"context"',
    '"database/sql"',
    '"fmt"',
    '"reflect"',
    '"strconv"',
    '"strings"',
    '"sync"',
    '"time"',
  ]

  third_party= [
    '"github.com/friendsofgo/errors"',
    '"github.com/volatiletech/null/v8"',
    '"github.com/volatiletech/sqlboiler/v4/boil"',
    '"github.com/volatiletech/sqlboiler/v4/queries"',
    '"github.com/volatiletech/sqlboiler/v4/queries/qm"',
    '"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"',
    '"github.com/volatiletech/strmangle"',
    '"app/util"'
  ]
